### ISSUE TITLE
病例控件文档段无法使用

### ISSUE THREAD

**Issue by StreakingMan** [tlzzu/SoDiaoEditor-Vue#1]
在v4版本是能用的，在vue中就不能使用了。能看看怎么回事嘛？谢谢~

**Comment by tlzzu** [comment]
我这里没有问题

**Comment by StreakingMan** [comment]
额，我换了台电脑也不行，就点击文档段没有任何反应，控制台没有任何信息，也没有产生请求。
用的是windows系统，chrome浏览器。
除了npm install 的时候报以下错误没有其他问题
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
大佬能试下将项目克隆下来再运行看看能正常使用文档段控件吗，因为我感觉可能不是我这边的问题，麻烦了~

**Comment by tlzzu** [comment]
qq:1923988647
说说你是怎么操作的

**Comment by StreakingMan** [comment]
克隆项目->npm install->npm run dev
![t1](https://user-images.githubusercontent.com/30397306/43594986-2d002da8-96ae-11e8-998f-c4724af65d91.jpg)
![t2](https://user-images.githubusercontent.com/30397306/43595585-a663e72e-96af-11e8-8b91-499932af8890.gif)
大致就是这样的

**Comment by madcodelife** [comment]
我也遇到这个问题了 请教一下怎么解决

**Comment by ziannchen** [comment]
> 在v4版本是能用的，在vue中就不能使用了。能看看怎么回事嘛？谢谢~

您好，请问这个问题解决了吗

**Comment by StreakingMan** [comment]
> 

不知这项目是否仍在维护，依稀记得项目是半开源的这功能免费版未开放

**Comment by ziannchen** [comment]
> > 
> 
> 不知这项目是否仍在维护，依稀记得项目是半开源的这功能免费版未开放

好吧。感谢你的回复
